### ISSUE TITLE
Connect client and server code through socket.io for communication

### ISSUE THREAD

**Issue by urvishvasani** [kenil-shah/Streamix#11]
A reliable connection is required between two entities to pass images back and forth for rendering purposes.

**Comment by urvishvasani** [comment]
For now, I've connected the server and client using socket.io. Basically, frames are being captured from the client's webcam continuously and are being sent over to the server. The server returns the same image using a socket and gets rendered on the client's web page. I'm not seeing any significant lag right now in this process but I'm curious to see how that it would turn out when the server processes the image frames and then send it over.

**Comment by kenil-shah** [comment]
Yep looks good. Since we have shifted to flask, I do'nt think that we need to worry about this.

**Comment by urvishvasani** [comment]
agree, I'm closing this issue now.
