### ISSUE TITLE
Dummy Frontend for Video Processing

### ISSUE THREAD

**Issue by kenil-shah** [kenil-shah/Streamix#7]

**Comment by kenil-shah** [comment]
Video Processing speed in JS is very slow, do we have any way to speed it up?

**Comment by harshitpatel96** [comment]
Moreover, we are also facing issues with doing inference using onnxjs in node.

**Comment by urvishvasani** [comment]
I guess, since most of our code (Virtual BG and EyeGaze) is written in python it makes sense to use flask. That would definitely boost up our speed because vectorized operations are very well implemented in numpy.

**Comment by kenil-shah** [comment]
Sounds fair. For now lets keep the JS frontend aside and lets start integrating our code with Flask.
