### ISSUE TITLE
Train EyeGaze models

### ISSUE THREAD

**Issue by kenil-shah** [kenil-shah/Streamix#8]

**Comment by kenil-shah** [comment]
Trained EyeGaze correction models, but as of now we would need to enter the distance from camera to center of the screen by computing manually. I think it is feasible to keep it that way as of now.

**Comment by urvishvasani** [comment]
Yes, I think that is okay for now. Later on, we can have a predefined n number of laptops with there assigned values and before the start of algorithm we can ask the user to select the laptop model based on which we can compute the distance from one-to-one mapping.
